{"name":"phys", "domains": ["phys.org"], "urls": ["https://phys.org/"], "article_extension": "/news", "xpath_title": ["//header[@class=\"content-head\"]//h1", "//article[@class=\"news-article\"]//h1"], "xpath_body": ["//section[@class=\"news-content\"]//article//p", "//article[@class=\"news-article\"]//div[@class=\"mt-4 article-main\"]//p"], "xpath_lead": ["//article[@class=\"news-article\"]//div[@class=\"mt-4 article-main\"]"]}
{"name":"sci_american", "domains": ["scientificamerican.com"], "urls": ["https://www.scientificamerican.com/"], "article_extension": "/article", "xpath_title": ["//title"], "xpath_body": ["//div[@class=\"article-progress\"]//p"], "xpath_lead": ["//header//p[@class=\"t_article-subtitle\"]"]}
{"name":"sci_daily", "domains": ["sciencedaily.com"], "urls": ["https://www.sciencedaily.com/"], "article_extension": "/releases", "xpath_title": ["//h1[@id=\"headline\"]"], "xpath_body": ["//div[@id=\"story_text\"]//p[not(@id=\"first\")]"], "xpath_lead": ["//div[@id=\"story_text\"]//p[@id=\"first\"]"]}
{"name":"sci_mag", "domains": ["sciencemag.org"], "urls": ["http://www.sciencemag.org/"], "article_extension": "/news", "xpath_title": ["//article[@class=\"primary primary--content\"]//h1[@class=\"article__headline\"]"], "xpath_body": ["//article[@class=\"primary primary--content\"]//p"], "xpath_lead": []}
{"name":"nature", "domains": ["nature.com"], "urls": ["https://nature.com/"], "article_extension": "/articles", "xpath_title": ["//article//h1[contains(@class, \"article-item__title\")]"], "xpath_body": ["//div[contains(@class, \"article__body\")]//p"], "xpath_lead": ["//article//div[contains(@class, \"article-item__teaser-text\")]"]}
{"name":"atlantic", "domains": ["theatlantic.com"], "urls": ["https://www.theatlantic.com/science", "https://www.theatlantic.com/health", "https://www.theatlantic.com/technology"], "article_extension": ["/science/archive", "/health/archive", "/technology/archive"], "xpath_title": ["//article[@id=\"main-article\"]//h1[@class=\"c-article-header__hed\"]"], "xpath_body": ["//article[@id=\"main-article\"]//p"], "xpath_lead": ["//article[@id=\"main-article\"]//div[@class=\"c-article-meta\"]//p[@class=\"c-dek\"]"]}
{"name":"northwestern", "domains": ["news.northwestern.edu"], "urls": ["https://news.northwestern.edu/science-and-tech/"], "article_extension": "/stories", "xpath_title": ["//div[@class=\"contain-970\"]//h2"], "xpath_body": ["//div[@id=\"news-story\"]//p"], "xpath_lead": ["//div[@class=\"contain-970\"]//p[@class=\"subhead\"]"]}
{"name":"stanford", "domains": ["news.stanford.edu"], "urls": ["https://news.stanford.edu/section/science-technology/", "http://med.stanford.edu/news/all-news.html"], "xpath_title": ["//div[@id=\"story-head\"]//h1", "//div[@class=\"news-title\"]//h1"], "xpath_body": ["//div[@id=\"story-content\"]//p"], "xpath_lead": ["//p[@class=\"excerpt\"]"]}
{"name":"harvard", "domains": ["news.harvard.edu"], "urls": ["https://news.harvard.edu/gazette/section/science-technology/", "https://news.harvard.edu/gazette/section/health-medicine/"], "article_extension": "/gazette/story", "xpath_title": ["//article//h1[@class=\"article-titles__title\"]"], "xpath_body": ["//div[@class=\"article-wrap\"]//p"], "xpath_lead": ["//article//h2[@class=\"article-subtitle\"]"]}
{"name":"rochester", "domains": ["rochester.edu"], "urls": ["https://www.rochester.edu/newscenter/category/news/sci-tech/"], "article_extension": "/newscenter", "xpath_title": ["//div[@class=\"post\"]//h1[contains(@class, \"post-title\")]"], "xpath_body": ["//div[@class=\"post\"]//p"], "xpath_lead": []}
{"name":"gw", "domains": ["gwtoday.gwu.edu"], "urls": ["https://gwtoday.gwu.edu/research-learning"], "article_extension": "", "xpath_title": ["//head[@class=\"major\"]//h1[@class=\"pane-title\"]"], "xpath_body": ["//div[@class=\"field-items\"]//p"], "xpath_lead": ["//h2[@class=\"subtitle\"]"]}
{"name":"ufl", "domains": ["ufl.edu"], "urls": ["https://news.ufl.edu/science/", "https://news.ufl.edu/health/"], "article_extension": ["/2019","/news", "/articles", "/science"], "xpath_title": ["//h1"], "xpath_body": ["//p"], "xpath_lead": ["//div[@class=\"kicker\"]//p"]}
{"name":"usf", "domains": ["www.usf.edu"], "urls": ["https://www.usf.edu/news/listing.aspx?category=Research%20and%20Innovation&year=s2019"], "article_extension": "/news", "xpath_title": ["//h1[@id=\"content-title\"]"], "xpath_body": ["//div[contains(@class, \"article-body\")]//p"], "xpath_lead": ["//p[@class=\"article-hero-caption\"]"]}